services:
  # Aplicación Flask
  app:
    build: .
    # Nombre del contenedor
    container_name: RIUL

    # localhost:5000 -> contenedor:5000
    ports:
      - "5000:5000"

    environment:
      DATABASE_URL: mysql+pymysql://inventory_user:inventory_password@db:3306/inventory_db
      JWT_SECRET_KEY: suero-clave-secret

    depends_on:
      db:
        condition: service_healthy

    restart: unless-stopped

  # Base de datos MySQL
  db:
    image: mysql:8.4
    container_name: RIUL_mysql

    environment:
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: inventory_user
      MYSQL_PASSWORD: inventory_password
      MYSQL_ROOT_PASSWORD: root_password

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data:


